require('svg4everybody')

require('./affix')
require('./autocomplete')
require('./autogrow')
require('./checkbox')
require('./checkbox-group')
require('./datepicker')
require('./datepicker-birthday')
require('./dropdown')
require('./dropzone')
require('./ie9-spinner')
require('./info')
require('./menu-collapsing')
require('./menu-main')
require('./menu-sliding')
require('./modal')
require('./notification')
require('./popover')
require('./progress-bar')
require('./segmented-control')
require('./site')

export default {}
