import 'svg4everybody'

import './affix'
import './autocomplete'
import './autogrow'
import './checkbox'
import './checkbox-group'
import './datepicker'
import './datepicker-birthday'
import './dropdown'
import './dropzone'
import './ie9-spinner'
import './info'
import './menu-collapsing'
import './menu-main'
import './menu-sliding'
import './modal'
import './modal2'
import './notification'
import './popover'
import './progress-bar'
import './segmented-control'
import './site'

export default {}
