import 'svg4everybody'

import './affix'
import './autocomplete'
import './autogrow'
import './checkbox-group'
import './checkbox'
import './dialog'
import './drawer'
import './dropdown'
import './dropzone'
import './fade'
import './footer'
import './ie9-spinner'
import './info'
import './menu-collapsing'
import './menu-main'
import './menu-sliding'
import './modal'
import './modal2'
import './notification'
import './popover'
import './progress-bar'
import './search'
import './segmented-control'
import './stroke'

import './bootstrap/affix'
import './bootstrap/alert'
import './bootstrap/button'
import './bootstrap/carousel'
import './bootstrap/collapse'
import './bootstrap/dropdown'
import './bootstrap/modal'
import './bootstrap/popover'
import './bootstrap/scrollspy'
import './bootstrap/tab'
import './bootstrap/tooltip'
import './bootstrap/transition'

export default {}
