hljs = require('highlight.js')
ignoreFm = require('./jade-filter-ignorefrontmatter')

module.exports = (jadeLang, jadeRuntime, jadeFilters) ->
  (text, options) ->
    # Remove front matter and render
    html = ignoreFm(jadeLang, jadeRuntime, jadeFilters)(text)

    # Remove first empty line generated by Jade
    html = html.replace(/^\n/g, '')

    # Enforce HTML syntax
    hljs.configure languages: [ 'html' ]

    code = jadeFilters('highlight', html)

    # Undo global hljs configs
    hljs.configure languages: null

    return code

# Copyright AXA Versicherungen AG 2015
