hljs = require('highlight.js')
normalizePath = require('metalsmith-relative/lib/normalize-path')

# Simple 'fallback' for metalsmith-relative
relative = (to) ->
  to

module.exports = (jadeLang, jadeRuntime, jadeFilters) ->
  (text, options) ->
    html = jadeLang.render(text, pretty: true, relative: relative)

    # Remove first empty line generated by Jade
    html = html.replace(/^\n/g, '')

    # enforce HTML syntax
    hljs.configure languages: [ 'html' ]

    code = jadeFilters('highlight', html)

    # undo global hljs configs
    hljs.configure languages: null

    return code

# Copyright AXA Versicherungen AG 2015
