import _ from 'lodash'

/**
 * Reads the `nav` property of every file.
 * It can be a string containing the slash-separated
 * path of the page in a menu of your choice.
 *
 * ```yml
 * ---
 * nav: main-menu/components/button
 * ---
 * ```
 *
 * Alternatively, you can assign your page to multiple menus
 * by assigning an array to the `nav` property.
 *
 * ```yml
 * ---
 * nav:
 *  - main-menu/components/header
 *  - featured-menu/header
 * ---
 * ```
 *
 * This plugin will collect all your files with the nav paths
 * and create one big structure that you can iterate over. This
 * structure will be saved to the Metalsmith metadata with the key `menu`.
 *
 * If you need the items as an array, you can find that under the key
 * `menuArray`. Every time there is a `children` key there will always
 * be a `childrenArray` key present too. The specialty about this array
 * representation of every level is that it is ordered by the `order`
 * property of your files.
 *
 * This is the structure generated by the two examples above.
 *
 * ```js
 * metadata.menu = {
 *   'main-menu': {
 *     name: 'main-menu',
 *     children: {
 *       'components': {
 *         name: 'components',
 *         children: {
 *           'button': {
 *             name: 'button',
 *             file: ...
 *           },
 *           'header': {
 *             name: 'header',
 *             file: ...
 *           }
 *         },
 *         childrenArray: [
 *           { } // the 'button' object
 *           { } // the 'header' object
 *         ]
 *       }
 *     },
 *     childrenArray: [
 *       { } // the 'main-menu' object
 *     ]
 *   },
 *   'featured-menu': {
 *     name: 'featured-menu',
 *     children: {
 *       'header': {
 *         name: 'header',
 *         file: ...
 *       }
 *     },
 *     childrenArray: [
 *       { } // the 'featured-menu' object
 *     ]
 *   }
 * }
 *
 * metadata.menuArray = [
 *   { } // the 'main-menu' object
 *   { } // the 'featured-menu' object
 * ]
 * ```
 */
const nav = () => (files, metalsmith, done) => {
  const menu = {}

  _.forEach(files, (file) => {
    if (!file.nav) return

    let value = file.nav

    if (!_.isArray(file.nav)) {
      // Ensure that nav is always an array
      value = [file.nav]
    }

    _.forEach(value, (path) => {
      const parts = path.split('/')

      let currentLevel = menu

      _.forEach(parts, (part) => {
        currentLevel.children = currentLevel.children || {}

        if (!currentLevel.children[part]) {
          currentLevel.children[part] = {
            name: part,
          }
        }

        currentLevel = currentLevel.children[part]
      })

      currentLevel.file = file
    })
  })

  const metadata = metalsmith.metadata()

  createChildrenArrays(menu)

  metadata.menu = menu.children
  metadata.menuArray = menu.childrenArray

  return done()
}

function createChildrenArrays(menu) {
  if (!menu.children) return menu

  const childrenArray = []

  _.forEach(menu.children, (child) => {
    childrenArray.push(createChildrenArrays(child))
  })

  menu.childrenArray = _.sortBy(childrenArray, (child) => {
    if (!child.file) return 0
    if (!child.file.order) return 0
    return child.file.order
  })

  return menu
}

export default nav
