module.exports = exports = function (jadeLang, jadeRuntime, jadeFilters) {
  var sampleIndex = 0;

  var template = [
    '.example!= sample',
    '.highlight',
    '  pre.highlight__listing.hljs: code(class=lang)!= htmlSource'
  ].join('\n');

  return function (text, options) {
    sampleIndex++;

    var sample = jadeLang.render(text, {
      pretty: true
    });

    // Remove first empty line generated by Jade
    sample = sample.replace(/^\n/g, '');

    var htmlSource = jadeFilters('highlight', sample);

    return jadeLang.render(template, {
      pretty: true,
      index: sampleIndex,
      sample: sample,
      htmlSource: htmlSource,
      lang: options.lang
    });
  };
};
