module.exports = exports = function (jadeLang, jadeRuntime, jadeFilters) {
  var sampleIndex = 0;

  var template = [
    '.sample.tab-panel',
    '  ul.sample__header.menu.menu--tabs.tab-panel__header',
    '    li.menu__item',
    '      a.menu__link.is-active(href="#", data-target="#sample_" + index + "_sample", data-toggle="tab") Sample',
    '    li.menu__item',
    '      a.menu__link(href="#", data-target="#sample_" + index + "_html", data-toggle="tab") HTML',
    '    li.menu__item',
    '      a.menu__link(href="#", data-target="#sample_" + index + "_jade", data-toggle="tab") Jade',
    '  .sample__body.tab-panel__content',
    '    .tab-panel__tab.is-active(id="sample_" + index + "_sample")!= sample',
    '    .tab-panel__tab(id="sample_" + index + "_html")',
    '      pre.hljs: code.html!= htmlSource',
    '    .tab-panel__tab(id="sample_" + index + "_jade")',
    '      pre.hljs: code.jade!= jadeSource'
  ].join('\n');

  return function (text) {
    sampleIndex++;

    var sample = jadeLang.render(text, {
      pretty: true
    });

    // Remove first empty line generated by Jade
    sample = sample.replace(/^\n/g, '');

    var htmlSource = jadeFilters('highlight', sample);
    var jadeSource = jadeFilters('highlight', text);

    return jadeLang.render(template, {
      pretty: true,
      index: sampleIndex,
      sample: sample,
      htmlSource: htmlSource,
      jadeSource: jadeSource
    });
  };
};
